services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - AUTH_TOKEN=${AUTH_TOKEN}
    restart: unless-stopped
volumes:
  node_modules:
