services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_QUICK_SYNC=${USE_QUICK_SYNC:-false}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./media:/media
    environment:
      - NODE_ENV=development
      - USE_QUICK_SYNC=${USE_QUICK_SYNC:-false}
    restart: unless-stopped
    devices:
      - ${DRI_DEVICE:-/dev/dri}:/dev/dri

volumes:
  node_modules:
