services:
  app:
    image: ghcr.io/martijnvanonz/optimized-versions-server:latest
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # New cache configuration
      - CACHE_RETENTION_HOURS=48
      - CLEANUP_INTERVAL_MINUTES=60
    restart: unless-stopped
    volumes:
      # Cache volume for persistent storage
      - ./cache:/usr/src/app/cache
      # Optional: logs volume
      - ./logs:/usr/src/app/logs
